tap "rfidresearchgroup/proxmark3"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Library for command-line editing
brew "readline"
# Zstandard is a real-time compression algorithm
brew "zstd"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# C parser in Python
brew "pycparser"
# C Foreign Function Interface for Python
brew "cffi"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Cryptographic recipes and primitives for Python
brew "cryptography"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Diff that understands syntax
brew "difftastic"
# Load/unload environment variables based on $PWD
brew "direnv"
# Perform least recently used (LRU) eviction of Docker images
brew "docuum"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# GNU grep, egrep and fgrep
brew "grep"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# GDI+-compatible API on non-Windows operating systems
brew "mono-libgdiplus"
# CLI for MySQL with auto-completion and syntax highlighting
brew "mycli"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Python dependency management tool
brew "pipenv"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Persistent key-value database, with built-in net interface
brew "redis"
# Programmatically correct mistyped console commands
brew "thefuck"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Application launcher and productivity software
cask "alfred"
# Display management tool
cask "betterdisplay"
# Open source IDE for exploring and testing APIs
cask "bruno"
# Plain-text editor for web pages, program source codes and more
cask "coteditor"
# All-in-one toolbox for developers
cask "devutils"
# Voice and text chat software
cask "discord"
# Web browser
cask "firefox"
# Desktop client for GitHub repositories
cask "github"
# Web browser
cask "google-chrome"
# Dedicated scratchpad for developers
cask "heynote"
# System monitoring app
cask "istat-menus"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Menu bar calendar
cask "itsycal"
# Software for Logitech devices
cask "logi-options+"
# Digital logic designer and simulator
cask "logisim-evolution"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Screenshot measurement and annotation tool
cask "shottr"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Application for inspecting installer packages
cask "suspicious-package"
# Native GUI tool for relational databases
cask "tableplus"
# Open-source BitTorrent client
cask "transmission"
# Batch rename utility
cask "transnomino"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Network protocol analyzer
cask "wireshark-app"
# Full-featured companion app to the YubiKey
cask "yubico-authenticator"
# Video communication and virtual meeting platform
cask "zoom"
mas "Affinity Designer 2", id: 1616831348
mas "Affinity Photo 2", id: 1616822987
mas "Affinity Publisher 2", id: 1606941598
mas "Bitwarden", id: 1352778147
mas "Color Picker", id: 1545870783
mas "iMovie", id: 408981434
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Ping", id: 1532271726
mas "The Unarchiver", id: 425424353
mas "Tim", id: 1449619230
mas "UPDF", id: 1619925971
mas "Xcode", id: 497799835
vscode "anthropic.claude-code"
vscode "bradlc.vscode-tailwindcss"
vscode "burkeholland.simple-react-snippets"
vscode "charliermarsh.ruff"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "github.vscode-pull-request-github"
vscode "grimmer.vscode-back-forward-button"
vscode "hashicorp.terraform"
vscode "ibm.output-colorizer"
vscode "inferrinizzard.prettier-sql-vscode"
vscode "kevinrose.vsc-python-indent"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "mechatroner.rainbow-csv"
vscode "mhutchie.git-graph"
vscode "mjmlio.vscode-mjml"
vscode "monosans.djlint"
vscode "mquandalle.graphql"
vscode "ms-python.debugpy"
vscode "ms-python.flake8"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode.powershell"
vscode "ms-vscode.vscode-serial-monitor"
vscode "ms-vsliveshare.vsliveshare"
vscode "mushan.vscode-paste-image"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "pkief.material-product-icons"
vscode "pranaygp.vscode-css-peek"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "samuelcolvin.jinjahtml"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "usernamehw.errorlens"
vscode "wayou.vscode-todo-highlight"
vscode "wyattferguson.jinja2-snippet-kit"
vscode "xabikos.javascriptsnippets"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
npm "alfred-open-in-vscode"
