#!/bin/bash
# chmod +x .git/hooks/pre-push

# Get the branch and repo name
branch=$(git rev-parse --abbrev-ref HEAD)
repo_name=$(basename $(git rev-parse --show-toplevel))

# Restricted branches and repos
restricted_branches=("main")
restricted_repositories=("zeus")

# If in a restricted repo, check for branch and ALLOW_MAIN_PUSH
if [[ " ${restricted_repositories[@]} " =~ " ${repo_name} " ]]; then
  if [ "$ALLOW_MAIN_PUSH" == "true" ]; then
    echo "⚠️ Bypassing restrictions for '$branch' in '$repo_name'."
    exit 0
  fi
  if [[ " ${restricted_branches[@]} " =~ " ${branch} " ]]; then
    echo "🚫 Pushing to '$branch' in '$repo_name' is not allowed. Use PR or 'ALLOW_MAIN_PUSH=true'."
    exit 1
  fi
fi

exit 0
